import React from 'react';

function Dashboard() {
    return (
        <div className="flex">
            {/* Sidebar */}
            {/*<div className="w-64 bg-gray-800 text-white p-4">*/}
            {/*    <h2 className="text-xl font-bold">Dashboard</h2>*/}
            {/*    <ul className="mt-4 space-y-2">*/}
            {/*        <li>Home</li>*/}
            {/*        <li>Settings</li>*/}
            {/*        <li>Users</li>*/}
            {/*        <li>Reports</li>*/}
            {/*    </ul>*/}
            {/*</div>*/}

            {/* Main Content Area */}
            <div className="flex-1">
                {/* Header */}
                <header className="bg-white p-4 flex justify-between items-center fixed top-0 left-0 sm:left-80 right-0 z-10 h-16">
                    <div className="flex space-x-4 mt-3">
                        <div className="relative hidden md:block group ml-4">
                            <input
                                id="search-bar"
                                type="text"
                                placeholder="Search here..."
                                name="text"
                                className="w-[20vw] pl-10 pr-4 py-2 rounded-xl border border-2 border-gray-300 opacity-80 focus:opacity-100 focus:w-[24vw] transition-all duration-200 ease-in-out outline-none hover:border-green-500 focus:border-green-500 group-hover:border-green-500"
                            />
                            <i className="fa fa-search absolute top-1/2 left-3 transform -translate-y-1/2 text-gray-600 group-hover:text-green-500"></i>
                        </div>
                    </div>

                    {/* Right Section */}
                    <div className="flex items-center space-x-4 pr-4 group cursor-pointer">
                        <img
                            src="https://via.placeholder.com/150"
                            alt="Profile"
                            className="w-10 h-10 rounded-full duration-150 group-hover:border-2 group-hover:border-green-500"
                        />
                        <div className="flex flex-col mr-4 group-hover:text-green-500">
                            <span className="font-semibold text-sm md:text-base duration-300 group-hover:text-green-500">
                                John Doe
                            </span>
                            <p className="text-xs text-gray-600 md:text-sm duration-300 group-hover:text-gray-500">
                                Admin
                            </p>
                        </div>
                    </div>
                </header>

                {/* Main Dashboard Content */}
                <div className="p-4 mt-16">
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                        {/* Stats Cards */}
                        <div className="bg-white p-4 rounded-lg shadow-md">
                            <h3 className="text-sm text-gray-600">Total Users</h3>
                            <p className="text-2xl font-semibold text-green-500">1500</p>
                        </div>
                        <div className="bg-white p-4 rounded-lg shadow-md">
                            <h3 className="text-sm text-gray-600">Active Sessions</h3>
                            <p className="text-2xl font-semibold text-green-500">120</p>
                        </div>
                        <div className="bg-white p-4 rounded-lg shadow-md">
                            <h3 className="text-sm text-gray-600">Pending Tasks</h3>
                            <p className="text-2xl font-semibold text-green-500">35</p>
                        </div>
                    </div>

                    {/* Recent Activities */}
                    <div className="mt-8">
                        <div className="bg-white p-4 rounded-lg shadow-md">
                            <h3 className="text-lg font-semibold">Recent Activities</h3>
                            <ul className="mt-4 space-y-2">
                                <li>User "John Doe" logged in</li>
                                <li>New task assigned to "Jane Smith"</li>
                                <li>Report generated by "Admin"</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default Dashboard;
